channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - numpy=2.4.1
  - pandas=2.3.0
  - matplotlib=3.7.2
  - seaborn=0.13.2
  - scipy=1.17.0
  - statsmodels=0.14.5
  - logomaker=0.8
  - mafft=7.520
  - mmseqs2=17.b804f